language: node_js
sudo: false,
node_js:
- stable
script:
- npm run prepublish
- npm test
notifications:
  slack:
    secure: esI54KRgxOXGMaj2XkL0hqzxbyPDvAjameywVBkFUFFxDJt3NnxtB4vkmA0iv5Qv+J9jqZ9UaVGnJhhsDJLYQXzkgLfONGiGE4JK/t55N8rGZDUB/3GRz0VMJBeAVYQai817IPoiSKAL88QDKYTuxtmfIrw1f36L6Dps6lWSowc2veYGrHRuTPPw7UtzZzGl29jx4Oahlh1JykC9TnyjbpRNRGsj11ru2k9J0cTEaIbD8Nu/26wBK/7+GJpY7lQ2JbD2ntJFBy965kz5ZXTbAwyBvHh4PLuy6SXNWcJd++ziYixmER+i/AK0lx8qEes+IbrYOeCnG88yWiNc5IZTqKuy9kW+U+N7RnFFy4l+mGaeNNOH9YZSot/ntLQJ6n2sEC4KhidkYPpZsU1tJZftX50LXQ9g0X2Kdsz7hQnqnyTG2OapTvxLBh/rTgLrPtvAzN2YZw6E/3qcEuxwVVkQJOkx2jiGL8TyOjNkXJ6YH2HTBM7E+8yaTRUy18q54MEOS0Mrm2/bPBpP25+V+gnOj+3CoCL+1iU/4FGfnXhxRfb9pUM+fiupLVi/8aW2k7YzVoai9CjAhSW72OxXvpyO1JFRCbi2tMi0oxfCIcSLToZGqpMdXGo/J5joT6SaAUjejM6VoKAzzSSnVUynep4CHwFKfPUV9ZertxhBa8n06mw=
deploy:
  provider: heroku
  app: mooskin
  api_key:
    secure: DAEJ2EIVlj3NhbyZ477UZsCHYNzVEpCyeu/By18cfv7YLc9M1ALs7AfYbG4fypYZG+cOpEGad9rFXpN0vrOfPofBRsOLIyJ9mOFZaLGHvnvnn/u8VN/wQhfCLImTwcde+qoCJzCPsl3lP1+Rv2elwfBZ6ZxRLBTvWnIv3JiIyCbyCTOvjo+pONMus7F8/3rX5EZJ7TPpn3Lcd35jeiE/XcKBm/OG3p3ADq4I6VMVQZNXvZ3Bzox+FGqvAGgFlxf9s7yRRps17j/LDddWI1jQCHcKprnDnLdTRcI3JkNx91gq9c202U2UVok4kAOPIa/1Riv2/VsgYmvMxTr5BCuJS4ZVRF9PNLhdM3zObMIHjmvMJFTo+UHGWdeGCvbNksmdK9ymRb3aFBa0wCj+8ItKNcP2L+js58y13l92wwcxbvHMftSx9FE460BYyLvdRVpe3hO280MlvTOIrxqkb+m4g6XOm+YZ1Q0OGhr376IYZL/4c09lMkTr0lCHvaFZ7WCEOczjjkL90uEoyek4a8r6eOXgrtejCOZshhCp4+RuRmiQxXtUieunZCgkYNFR0olvkHjfIT9CtAggyogdglo2MYbxd5bZhzCntqflPIxQ3s8VIarXEbalj5BnaeN8BqhNT5q36Rpyd4CWGJuj6kyuTCC3qBNEZ2aFJ9Pof9woUvo=
