language: node_js
sudo: false,
node_js:
- stable
script:
- npm run prepublish
- npm test
notifications:
  slack:
    secure: esI54KRgxOXGMaj2XkL0hqzxbyPDvAjameywVBkFUFFxDJt3NnxtB4vkmA0iv5Qv+J9jqZ9UaVGnJhhsDJLYQXzkgLfONGiGE4JK/t55N8rGZDUB/3GRz0VMJBeAVYQai817IPoiSKAL88QDKYTuxtmfIrw1f36L6Dps6lWSowc2veYGrHRuTPPw7UtzZzGl29jx4Oahlh1JykC9TnyjbpRNRGsj11ru2k9J0cTEaIbD8Nu/26wBK/7+GJpY7lQ2JbD2ntJFBy965kz5ZXTbAwyBvHh4PLuy6SXNWcJd++ziYixmER+i/AK0lx8qEes+IbrYOeCnG88yWiNc5IZTqKuy9kW+U+N7RnFFy4l+mGaeNNOH9YZSot/ntLQJ6n2sEC4KhidkYPpZsU1tJZftX50LXQ9g0X2Kdsz7hQnqnyTG2OapTvxLBh/rTgLrPtvAzN2YZw6E/3qcEuxwVVkQJOkx2jiGL8TyOjNkXJ6YH2HTBM7E+8yaTRUy18q54MEOS0Mrm2/bPBpP25+V+gnOj+3CoCL+1iU/4FGfnXhxRfb9pUM+fiupLVi/8aW2k7YzVoai9CjAhSW72OxXvpyO1JFRCbi2tMi0oxfCIcSLToZGqpMdXGo/J5joT6SaAUjejM6VoKAzzSSnVUynep4CHwFKfPUV9ZertxhBa8n06mw=
deploy:
  provider: npm
  email: gentgaashi@gmail.com
  skip_cleanup: true
  api_key:
    secure: ksTuhb0MfaFvk3aIlU7goL6D+3u37W5mGYwVFib5KKpOFv+GrsXsqetaeS0ttQAmTkL/Mssldu0EhqVRDvvRvscIDEpxb7nj6fY/KzY1pxpNZ6rjcukOgM2xxg7B1/Sj/9uykJE15rTpt3CnXb9h5m3UfCuv771R6bBKv86uUZ5eM1y5/xQpgmuUYFBiZptSPihdoZbdrd9olUZSDbCzCk9i86taLHoC0wobxLWGlO2tNFVeimmfP/0+GaFOeItrE8Oigf40dCBsJcSBVjySEGvPXjj+/bH/GhClJskYennwcn3HZgLVgebM6olMwmjCZJkdT/KBk6gYORef2Xy4frI0frzXwcDFHtT+7Y7Z2FsAZjj5mimtczeNoRmZXE+sBpN7V5oauxnfcIIhlCU0MXwHTFYH+npNr74SyaE3h698cBZs6y7Nd1rRKvUP7yyTlsyH9U6js1S9+nithXCjOFhl1JWf6LjaAxNUhUupHRvFO+LCEh5kyg6LEY8y6ZjEW6o4r1BCS0jGiymS+79Q2vzNcQ/+uIoos2PQTq3C3tsD0aBCl3W871VHqN/Lp67BeX54GDR8CqJMGLZFvoXZiJLaL7+juvNrUEEZg0ODZ1Gvsd/xptJ09Y4SkZifmXU2wxXG/2lULm5YIjzx32V1QTs9xfkZdSc3favtMnFcijA=
  on:
    tags: true
    repo: moosend/mooskin-ui
    branch: master
