language: node_js
sudo: false,
node_js:
- stable
script:
- npm run prepublish
- npm test
notifications:
  slack:
    secure: esI54KRgxOXGMaj2XkL0hqzxbyPDvAjameywVBkFUFFxDJt3NnxtB4vkmA0iv5Qv+J9jqZ9UaVGnJhhsDJLYQXzkgLfONGiGE4JK/t55N8rGZDUB/3GRz0VMJBeAVYQai817IPoiSKAL88QDKYTuxtmfIrw1f36L6Dps6lWSowc2veYGrHRuTPPw7UtzZzGl29jx4Oahlh1JykC9TnyjbpRNRGsj11ru2k9J0cTEaIbD8Nu/26wBK/7+GJpY7lQ2JbD2ntJFBy965kz5ZXTbAwyBvHh4PLuy6SXNWcJd++ziYixmER+i/AK0lx8qEes+IbrYOeCnG88yWiNc5IZTqKuy9kW+U+N7RnFFy4l+mGaeNNOH9YZSot/ntLQJ6n2sEC4KhidkYPpZsU1tJZftX50LXQ9g0X2Kdsz7hQnqnyTG2OapTvxLBh/rTgLrPtvAzN2YZw6E/3qcEuxwVVkQJOkx2jiGL8TyOjNkXJ6YH2HTBM7E+8yaTRUy18q54MEOS0Mrm2/bPBpP25+V+gnOj+3CoCL+1iU/4FGfnXhxRfb9pUM+fiupLVi/8aW2k7YzVoai9CjAhSW72OxXvpyO1JFRCbi2tMi0oxfCIcSLToZGqpMdXGo/J5joT6SaAUjejM6VoKAzzSSnVUynep4CHwFKfPUV9ZertxhBa8n06mw=
deploy:
  provider: heroku
  app: mooskin
  api_key:
    secure: dxC1El3XU953rHNfTICiGSfagotArsQ7kBavOYNmCRLjC1jCBI0OcdxRlEySI9oTArA39geqZOoov2SaXQWhAzwpW41ctPOdXfJ9jqr995c5jfTzOk36i1Cjc2FYYXsm3flxG+Ac21crUWJK/1hNWqgF7OfTFfLpNDe+Li/PlcbtbmtPjoEW8htLtuzg3x681b6euqTMVERVreMFVHoY6beiLvb0cYQwpsx/yNy9gOwPwT7WCyKJFWb2CFpKDrt3lI55EuCKpmESLwf1UhKy7BxJvhThM7YrAkxV9DxXtUFsRASdMpA8UU3VzXaetvM+MApZ36eQy/9Q6mphRfDy7Av2U65jgKYeSgZRb/zaWepXx4gv66FTXvOtCoyzLlWOywkbxfuhRIDfZ6WEHBGQEzvaCkKfN0qBQCLxBj3Xcg4EB4POac4fK/L7UVA+EUK+2bnApfRgOVDwV3jIUL7K4T7Z2rBVhA6RnkWF/fy2nYkQlrTyW/dg0LIbCGm3rdKLzVCYA5UQxkTh6gXwHXJJq/yr+DCKoiBNhriuOu2OjwuwyTb6+ZU9yYlH82EwnObfVETMS3aN1P1XqEVTr3tdoICywr1xpGVjN8Jl7+TzOhW82ejdKpnQO20iM9fwVruOo77J5XfQ7u3ouZ+F3rdPr/khkHaomBeRhwqYvOFHw0U=